spring.application.name=todaylist
spring.datasource.url=jdbc:postgresql://localhost:5432/todaylist
spring.datasource.username=postgres
spring.datasource.password=1308
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.data-base-platform=org.hibernate.dialect.PostgresPlusDialect